### ISSUE TITLE
Not working when spawn stdio: 'inherit'?

### ISSUE THREAD

**Issue by tunnckoCore** [doowb/capture-stream#2]
Should it work?

``` js
var spawn = require('cross-spawn')
var capture = require('capture-stream')

var stream = spawn('npm', ['show verb'], {stdio: 'inherit'})
var restore = capture(stream)
console.log(restore()) // => []
```

Or I'm missing something? I it would be great. I found http://npm.im/superspawn, but it's ugly and too big and "reinventing the wheel". I also have done some capturing in the past with `async-exec-cmd`, so I can think for something and can do a PR. I'm starting to work on this now, because I need it.

**Comment by doowb** [comment]
`capture-stream` takes a readable stream like [process.stdout](https://github.com/doowb/capture-stream#usage) to capture. That spawn library in your example is creating a new "process" object that will have the streams on it. I think you can do something like this:

``` js
var spawn = require('cross-spawn')
var capture = require('capture-stream')

var proc = spawn('npm', ['show verb'], {stdio: 'inherit'})
var restore = capture(proc.stdout)
console.log(restore())
```

I haven't tried this out with `spawn` yet, so I'm not sure if you need to capture the stream before calling `spawn` or not. If so, try `var restore = capture(process.stdout)` before calling `spawn`.

**Comment by tunnckoCore** [comment]
Yea, I forgot to mention that `proc.stdout` and again not works.
In anyway I created http://npm.im/capture-spawn.

> before calling spawn.

make sense, will try when have time

**Comment by doowb** [comment]
Nice library. I think it's solving a different problem than this one.

**Comment by doowb** [comment]
Closing since this should be used directly on a stream.
