### ISSUE TITLE
Missing tags

### ISSUE THREAD

**Issue by nirmalkv** [doowb/capture-stream#3]
This git repo is missing tags, please add them.

**Comment by jonschlinkert** [comment]
> missing tags

Specifically which tags are missing?

**Comment by nirmalkv** [comment]
I am not sure, when I tried to package your module using npm2deb, it
downloaded npm dist tarballs from fakeupstream. It said that upstream git
repo is missing tags. I will enquire about this issue with a debian
developer and contact you.

Thanks!

**Comment by pravi** [comment]
@jonschlinkert npmjs.com has 0.1.2 version, but this repo has only 0.1.1 tag.

**Comment by doowb** [comment]
@pravi, thanks for the additional information. I added the tag here.

I'm curious about how Debian handles npm modules. Does something throw an error when a module is missing a tag on GitHub but is still available on npm?

We have an [updater for git tags](https://github.com/update/updater-git-tags) that we use now, but projects that haven't needed updating recently might still be missing tags.

**Comment by pravi** [comment]
@doowb we use https://github.com/LeoIannacone/npm2deb to create the debian package from a node module. We prefer github tarballs for 2 reasons, 

1. npm dist tarballs may have prebuilt files (minified, browserified, transpiled, etc). We should use the source code used by upstream for modification to create the debian package. 
2. npm dist tarballs may not include tests.

So when github repo is missing tags corresponding to npm release, npm2deb falls back to using npm dist tarballs, but gives a warning.

**Comment by doowb** [comment]
Thanks!

Is there a place the debian packages are published?
Is it something that a developer does on their own or are these bundled with debian?

I know I've seen you post on other repositories about bundling for debian, but I haven't looked into how that works. I usually use ubuntu and mac osx, so I haven't had a chance to learn about debian.

**Comment by pravi** [comment]
> Is there a place the debian packages are published?

You can find details of any package from tracker.debian.org. For example, https://tracker.debian.org/pkg/node-babylon shows the details of babylon node module (we add node- prefix to node modules).

> Is it something that a developer does on their own or are these bundled with debian?

Our main aim for packaging these node modules are to make build tools (like [grunt](https://tracker.debian.org/pkg/grunt) , [gulp](https://tracker.debian.org/pkg/node-gulp) , [webpack](https://tracker.debian.org/pkg/node-webpack)) available in debian so libraries like [handlebars](https://tracker.debian.org/pkg/libjs-handlebars)  for applications like [gitlab](https://tracker.debian.org/pkg/gitlab)  and diaspora (apt-get install gitlab will setup a gitlab instance for you) can be built from their source repos. So the end goal is to make it possible for people who are not specialized in nodejs, ruby or other languages to be able to setup web based services with just apt.

> I know I've seen you post on other repositories about bundling for debian, but I haven't looked into how that works. I usually use ubuntu and mac osx, so I haven't had a chance to learn about debian.

Ubuntu is derived from debian and all packages that goes to debian gets pulled into Ubuntu as well.

**Comment by doowb** [comment]
Thanks for all the information! I don't put together that the debian packages are what `apt-get` installs, but now I understand.
